# k3d-specific configuration for testing
# Removes hardware-specific requirements that k3d doesn't support

# Use local images for k3d
image:
  pullPolicy: IfNotPresent  # Use local images when available

# Reduce resource requirements for k3d testing
resources:
  gnb:
    limits:
      cpu: 8              # Increased from 4 for better compilation and runtime performance
      memory: 8Gi         # Increased from 2Gi for C++ compilation
      hugepages1Gi: ""    # Explicitly override to empty string
      # hugepages-1Gi: 4Gi  # Removed - k3d doesn't support hugepages
    requests:
      cpu: 4              # Increased from 2 for better compilation and runtime performance
      memory: 4Gi         # Increased from 1Gi for C++ compilation
      hugepages1Gi: ""    # Explicitly override to empty string
      # hugepages-1Gi: 4Gi  # Removed - k3d doesn't support hugepages
  jbpf_proxy:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 200m           # Reduced from 500m
      memory: 256Mi       # Reduced from 500Mi
  jrtc:
    limits:
      cpu: 1              # Increased from 500m 
      memory: 4Gi         # ushasi - Increased from 2Gi to prevent OOM with JBPF memory
      hugepages2Gi: ""    # Explicitly override to empty string for k3d
      # hugepages2Gi: 2Gi   # Removed - k3d doesn't support hugepages
    requests:
      cpu: 500m           # Increased from 200m
      memory: 2Gi         # ushasi - Increased from 1Gi to prevent OOM with JBPF memory
      hugepages2Gi: ""    # Explicitly override to empty string for k3d
      # hugepages2Gi: 2Gi   # Removed - k3d doesn't support hugepages
  open5gs:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

# Remove SR-IOV requirements for k3d testing
duConfigs:
  du1:
    midhaul:
      ip: 192.168.110.233
    cells: null  # Explicitly set to null to override default cell1

# Keep basic networking config but remove SR-IOV resources
sriov:
  cniVersion: 0.3.1
  cucp_ip: 192.168.101.205
  cucp_prefix: 24
  cucp_gateway: 192.168.101.1
  cuup_ip: 192.168.110.205
  cuup_prefix: 24
  cuup_gateway: 192.168.110.1
  # resourceName: "intel.com/intel_810_1"  # Removed - not available in k3d
  resourceName: ""  # Set to empty string to avoid template issues

# Disable hardware-specific features
das:
  enabled: false
dmimo:
  enabled: false

# Configure 5gc for k3d
open5gs:
  enabled: false          # Disabled - Open5GS removed from srsRAN pod
  image: "janus-latest-5gc:latest"  # Use the locally built image
  expose_ngap: false

# Fix missing volume paths for k3d
jbpf:
  codelets_vol_mount: "/home/wcsng-23/gitrepos/srsran-jbpf/codelets"

jrtc_controller:
  apps_vol_mount: "/home/wcsng-23/gitrepos/srsran-jbpf/jrtc_apps"

srsran:
  source_path: "/home/wcsng-23/gitrepos/srsran-jbpf/containers/Docker/srsRAN_Project"

jrtc:
  utils_path: "/home/wcsng-23/gitrepos/srsran-jbpf/utils"
  env_file_path: "/home/wcsng-23/gitrepos/srsran-jbpf/.env"
  set_vars_path: "/home/wcsng-23/gitrepos/srsran-jbpf/set_vars.sh"

jbpf_extended:
  protobuf_path: "/home/wcsng-23/gitrepos/srsran-jbpf/jbpf_protobuf" 