PROTO_AND_SCHEMA := \
	rrc_ue_add^rrc_ue_add \
	rrc_ue_procedure^rrc_ue_procedure \
	rrc_ue_remove^rrc_ue_remove \
	rrc_ue_update_context^rrc_ue_update_context \
	rrc_ue_update_id^rrc_ue_update_id

include ../Makefile.defs
include ../Makefile.common

