PROTO_AND_SCHEMA := \
	ue_contexts^du_ue_ctx_creation \
	ue_contexts^du_ue_ctx_update_crnti \
	ue_contexts^du_ue_ctx_deletion \
	ue_contexts^cucp_ue_ctx_creation \
	ue_contexts^cucp_ue_ctx_update \
	ue_contexts^cucp_ue_ctx_deletion \
	ue_contexts^e1ap_cucp_bearer_ctx_setup \
	ue_contexts^e1ap_cuup_bearer_ctx_setup \
	ue_contexts^e1ap_cuup_bearer_ctx_release

include ../Makefile.defs
include ../Makefile.common
