PROTO_AND_SCHEMA := \
	mac_sched_crc_stats^crc_stats \
	mac_sched_bsr_stats^bsr_stats \
	mac_sched_phr_stats^phr_stats \
	mac_sched_uci_stats^uci_stats \
	mac_sched_harq_stats^harq_stats

include ../Makefile.defs
include ../Makefile.common
