PROTO_AND_SCHEMA := \
	mac_sched_crc_stats^mac_stats \
	mac_sched_ul_bsr_indication^mac_sched_ul_bsr_indication \
	mac_sched_crc_indication^mac_sched_crc_indication \
	mac_sched_ul_phr_indication^mac_sched_ul_phr_indication

include ../Makefile.defs
include ../Makefile.common

#	mac_sched_crc_stats^mac_stats \
#
